service: nest-api
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false

  custom:
    enable_optimize:
      local: false
    webpack:
      includeModules:
        forceInclude:
          - pg
          - pg-hstore
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 30
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
  vpc:
    securityGroupIds:
      - sg-a0b6aeee
    subnetIds:
      - subnet-397f2573

functions:
  web-app:
    handler: handler.webApp
    events:
      - http: ANY {proxy+}
      - http: ANY /
  migrations-up:
    handler: sequelize/migration-runner.migrationsUp
    package:
      patterns:
        - migrations/**
  migrations-down:
    handler: sequelize/migration-runner.migrationsDown
    package:
      patterns:
        - migrations/**
  migrations-status:
    handler: sequelize/migration-runner.migrationsStatus
    package:
      patterns:
        - migrations/**
