service: nest-api
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false

  custom:
    enable_optimize:
      local: false
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 10
functions:
  web-app:
    handler: handler.webApp
    events:
      - http: ANY {proxy+}
      - http: ANY /
