service: nest-api-2
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false

  custom:
    enable_optimize:
      local: false
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 10
functions:
  web-app:
    handler: handler.webApp
    events:
      - http: ANY {proxy+}
      - http: ANY /
  migrations-up:
    handler: sequelize/migration-runner.migrationsUp
  migrations-down:
    handler: sequelize/migration-runner.migrationsDown
  migrations-status:
    handler: sequelize/migration-runner.migrationsStatus

environment:
  PG_HOST: ${env:PG_HOST}
  PG_USERNAME: ${env:PG_USERNAME}
  PG_PASSWORD: ${env:PG_PASSWORD}
